tap "dbt-labs/dbt"
tap "facebook/fb"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "glib"
brew "harfbuzz"
brew "apktool"
brew "sqlite"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "boost"
brew "bundletool"
brew "libssh2"
brew "openldap"
brew "curl"
brew "unixodbc"
brew "freetds"
brew "libavif"
brew "gd"
brew "libpq"
brew "php"
brew "composer"
brew "folly"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "srt"
brew "ffmpeg"
brew "frum"
brew "gh"
brew "git"
brew "gnupg"
brew "gobject-introspection"
brew "grep"
brew "httpd"
brew "jq"
brew "kompose"
brew "mas"
brew "n"
brew "nghttp2"
brew "node", link: false
brew "phpstan"
brew "pidof"
brew "pre-commit"
brew "python@3.11"
brew "rbenv"
brew "tfenv"
brew "watchman"
brew "xcbeautify"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "facebook/fb/idb-companion"
cask "azure-data-studio"
cask "docker"
cask "figma"
cask "flipper"
cask "gimp"
cask "git-credential-manager"
cask "google-cloud-sdk"
cask "inkscape"
cask "insomnia"
cask "mailspring"
cask "ngrok"
cask "openvpn-connect"
cask "p4v"
cask "phpstorm"
cask "react-native-debugger"
cask "sequel-ace"
cask "slack"
cask "spotify"
cask "steam"
cask "temurin11"
cask "visual-studio-code"
cask "vlc"
mas "Boop", id: 1518425043
mas "ColorSlurp", id: 1287239339
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft To Do", id: 1274495053
mas "Microsoft Word", id: 462054704
mas "Simplenote", id: 692867256
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
